
/*Producer produced-0
Producer produced-1
Consumer consumed-0
Consumer consumed-1
Producer produced-2
Consumer consumed-2
Producer produced-3
Consumer consumed-3
Producer produced-4
Producer produced-5
Consumer consumed-4
Consumer consumed-5
Producer produced-6
Consumer consumed-6
Producer produced-7
Producer produced-8
Consumer consumed-7
Consumer consumed-8
Producer produced-9
Producer produced-10
Consumer consumed-9
Consumer consumed-10
Producer produced-11
Producer produced-12
Consumer consumed-11
Consumer consumed-12
Producer produced-13
Producer produced-14
Consumer consumed-13
Consumer consumed-14
Producer produced-15
Producer produced-16
Consumer consumed-15
Consumer consumed-16
Producer produced-17
Producer produced-18
Consumer consumed-17
Consumer consumed-18
Producer produced-19
Producer produced-20
Consumer consumed-19
Consumer consumed-20
.........
 */